name: aprendizaje_automatico
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - scipy           
  - xgboost
  - shap
  - matplotlib
  - seaborn
  - plotly
  - python-kaleido
  - jupyter
  - kneed
  - tabulate
  - pyarrow
  - pyyaml
  - pip
  - pip:
      - minisom     