name: aprendizaje_automatico
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scikit-learn
  - xgboost
  - seaborn
  - pandas
  - tabulate
  - pyarrow
  - shap
  - matplotlib
  - numpy
  - jupyter
  - pyyaml