{
  "hash": "6c0ac01f1ebcd5dd548535e03adecbff",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Análisis Exploratorio de Datos\"\n---\n\nUna vez finalizada la fase de preprocesamiento e ingeniería de variables, disponemos de un conjunto de datos consolidado, depurado y enriquecido. El objetivo de este capítulo es desarrollar un Análisis Exploratorio de Datos (EDA) estructurado que nos permita comprender más acerca de los datos que tenemos y la relación entre sus distintas variables.\n\n## Importación de librerías\n\nComenzamos importando las librerías necesarias para esta sección\n\n::: {#importar-librerias-eda .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom scipy import stats\n```\n:::\n\n\n## Carga de datos\n\nProcedemos a la lectura del archivo de datos unificado de las 3 ediciones junto con todos los cambios realizados en el capítulo de preprocesado. \n\n::: {#carga-datos-eda .cell execution_count=2}\n``` {.python .cell-code}\ndf_boston = pd.read_parquet(\"../data/processed/boston_post_eda.parquet\")\n```\n:::\n\n\n## Análisis Univariante\n\nEl objetivo de esta sección es comprender mejor la distribución de las variables por separado. Para ello, comenzamos revisando la distribución de las dos variables objetivo. \n\n### Distribución de las variables objetivo (`hit_the_wall` y `official_time`)\n\nNuestro estudio aborda dos enfoques predictivos distintos: un problema de regresión sobre el tiempo final en meta (`official_time`) y un problema de clasificación binaria para la detección del colapso fisiológico (`hit_the_wall`). A continuación, inspeccionamos la composición y distribución de ambas metas.\n\n::: {#cell-eda-distribucion-objetivos .cell execution_count=3}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(12, 5))\n\n# 1. Distribución del Tiempo Oficial (sólo curva de densidad KDE)\ntiempo_horas = df_boston['official_time'] / 3600\nsns.kdeplot(\n    tiempo_horas, ax=axes[0], color=\"#2b5c8f\", linewidth=2.5, \n    fill=True, alpha=0.1\n)\naxes[0].set_title(\"Distribución del Tiempo Oficial en Meta\", fontsize=13)\naxes[0].set_xlabel(\"Tiempo en Meta (Horas)\")\naxes[0].set_ylabel(\"Densidad\")\n\n# 2. Proporción de la variable binaria del Muro (hit_the_wall)\nmuro_counts = df_boston['hit_the_wall'].value_counts()\nsns.barplot(\n    x=muro_counts.index, y=muro_counts.values, ax=axes[1], \n    hue=muro_counts.index, palette=[\"#2ca02c\", \"#d62728\"], legend=False\n)\naxes[1].set_title(\"Proporción de Impacto contra el Muro\", fontsize=13)\naxes[1].set_xticklabels([\"Ritmo Constante (0)\", \"Muro / Colapso (1)\"])\naxes[1].set_ylabel(\"Número de Corredores\")\n\n# Añadimos las etiquetas de porcentaje de las barras\ntotal_corredores = len(df_boston)\nfor p in axes[1].patches:\n    porcentaje = f\"{100 * p.get_height() / total_corredores:.2f}%\"\n    axes[1].annotate(\n        porcentaje, \n        (p.get_x() + p.get_width() / 2., p.get_height()),\n        ha='center', va='top', fontsize=12, fontweight='bold',\n        color='white', \n        xytext=(0, -20), textcoords='offset points'  \n    )\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](02_eda_files/figure-html/eda-distribucion-objetivos-output-1.png){#eda-distribucion-objetivos width=1141 height=468}\n:::\n:::\n\n\nLa distribución del tiempo oficial presenta una clara asimetría positiva, concentrando a la gran mayoría del pelotón entre las 3 horas y cuarto y las 4 horas, lo que evidencia el alto nivel de exigencia y la criba previa de marcas que requiere esta competición.\n\nPor su parte, la variable del muro muestra que el 79.78% de los atletas logran mantener un ritmo constante, mientras que el 20.22% colapsan y sufren una deceleración severa en la segunda mitad de la prueba. Esta proporción confirma que nos enfrentamos a un problema de clasificación desbalanceado, un factor clave que deberá tenerse en cuenta al configurar los pesos en los modelos predictivos posteriores.\n\n\n\n### Distribución de las variables Edad y Género\n\nEn este apartado, vamos a visualizar la distribución de las variables de Edad y Género:\n\n::: {#cell-eda-distribucion-demografia .cell execution_count=4}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(12, 5))\n\n\nsns.kdeplot(\n    df_boston['age'], ax=axes[0], color=\"#2b5c8f\", linewidth=2.5, \n    fill=True, alpha=0.1\n)\naxes[0].set_title(\"Distribución de la Edad de los Participantes\", \n    fontsize=13)\naxes[0].set_xlabel(\"Edad (Años)\")\naxes[0].set_ylabel(\"Densidad\")\n\n\n\norden_genero = ['M', 'F']\netiquetas_fijas = ['Masculino (M)', 'Femenino (F)']\ncolores_fijos = [\"#4a6491\", \"#8c2d2d\"]\n\n\ngenero_counts = df_boston['gender'].value_counts().reindex(orden_genero)\n\nsns.barplot(\n    x=genero_counts.index, \n    y=genero_counts.values, \n    ax=axes[1], \n    order=orden_genero,\n    palette=colores_fijos,\n    hue=genero_counts.index,\n    legend=False\n)\n\naxes[1].set_title(\"Proporción de Participación por Género\", \n    fontsize=13)\naxes[1].set_xticklabels(etiquetas_fijas) \naxes[1].set_ylabel(\"Número de Corredores\")\n\n\ntotal_n = len(df_boston)\nfor p in axes[1].patches:\n    \n    porcentaje = f\"{100 * p.get_height() / total_n:.2f}%\"\n    axes[1].annotate(\n        porcentaje, \n        (p.get_x() + p.get_width() / 2., p.get_height()),\n        ha='center', va='top', fontsize=12, fontweight='bold',\n        color='white', \n        xytext=(0, -20), textcoords='offset points'\n    )\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](02_eda_files/figure-html/eda-distribucion-demografia-output-1.png){#eda-distribucion-demografia width=1141 height=468}\n:::\n:::\n\n\nEl perfil demográfico de los participantes refleja una población madura y equilibrada, con una mayoría de corredores situados en torno a los 45 años, lo que evidencia la experiencia necesaria para alcanzar los tiempos de calificación exigidos en Boston. En cuanto al género, la muestra presenta una paridad notable con un 54.57% de hombres frente a un 45.43% de mujeres, una distribución muy positiva para el entrenamiento de los posteriores modelos.\n\n\n### Top 10 países\n\nCon el objetivo de visualizar las nacionalidades de los atletas, a continuación vamos a identificar las 10 naciones con mayor volumen de participación. \n\n::: {#eda-top-paises .cell execution_count=5}\n``` {.python .cell-code}\n# 1. Calculamos los 10 países\ntop_10_paises = (\n    df_boston['country_residence']\n    .value_counts()\n    .head(10)\n    .to_frame()\n    .reset_index()\n)\n\ntop_10_paises.columns = ['País', 'Número de Corredores']\ntotal_corredores = len(df_boston)\ntop_10_paises['Porcentaje (%)'] = (\n    (top_10_paises['Número de Corredores'] / total_corredores) * 100\n).round(2)\n\nprint(top_10_paises.to_markdown(index=False))\n```\n| País   |   Número de Corredores |   Porcentaje (%) |\n|:-------|-----------------------:|-----------------:|\n| USA    |                  64001 |            80.97 |\n| CAN    |                   6135 |             7.76 |\n| GBR    |                   1063 |             1.34 |\n| MEX    |                    757 |             0.96 |\n| GER    |                    569 |             0.72 |\n| JPN    |                    488 |             0.62 |\n| AUS    |                    469 |             0.59 |\n| ITA    |                    466 |             0.59 |\n| CHN    |                    427 |             0.54 |\n| BRA    |                    425 |             0.54 |\n:::\n\n\nLa tabla refleja que EEUU es el país que más participantes concentra, casi el 81% de los participantes. De cara al entrenamiento de los modelos, manejar una variable con tantos países distintos puede complicar el aprendizaje del algoritmo debido a la gran cantidad de categorías con muy pocos datos. Por ello, una solución eficaz para mejorar la precisión será simplificar esta información en la fase de modelado, ya sea creando una variable binaria (EE. UU. frente al Resto del mundo) o agrupando los países por continentes, facilitando así que el modelo identifique patrones geográficos de rendimiento de manera más clara y robusta.\n\n::: {#eda-eliminar-enviroment .cell execution_count=6}\n``` {.python .cell-code}\ndel genero_counts, muro_counts, tiempo_horas, top_10_paises, axes, colores_fijos, etiquetas_fijas, fig, orden_genero, p, porcentaje, total_corredores, total_n\n```\n:::\n\n\n## Análisis Bivariado y Multivariado\n\nEl objetivo de esta sección es identificar patrones y relaciones entre variables a través de un análisis bivariado y multivariado. \n\n### Tiempo final vs Edad vs Género\n\nA continuación, vamos a comprobar las distribuciones del tiempo tardado en la maratón en intervalos de 5 años de edad para ver cuál es el mejor rango de edad en cuanto a rendimiento. Además, vamos a agrupar dichos resultados por género para obtener una gráfica distinta para cada uno.\n\n::: {#cell-eda-boxplot-edad-tiempo .cell execution_count=7}\n``` {.python .cell-code}\ndf_boston['age_bins'] = pd.cut(df_boston['age'], \nbins=range(15, 86, 5))\n\nfig, axes = plt.subplots(2, 1, figsize=(12, 10))\n\n# Convertimos a horas para la visualización\ndf_boston['official_hours'] = df_boston['official_time'] / 3600\n\n# Gráfico para Hombres\nsns.boxplot(\n    data=df_boston[df_boston['gender'] == 'M'], \n    x='age_bins', y='official_hours', ax=axes[0], color=\"#4a6491\", fliersize=1\n)\naxes[0].set_title(\"Hombres: Tiempo Final por Rango de Edad\", \nfontsize=14, fontweight='bold')\naxes[0].set_xlabel(\"\")\naxes[0].set_ylabel(\"Tiempo en Meta (Horas)\")\n\n# Gráfico para Mujeres\nsns.boxplot(\n    data=df_boston[df_boston['gender'] == 'F'], \n    x='age_bins', y='official_hours', ax=axes[1], color=\"#8c2d2d\", fliersize=1\n)\naxes[1].set_title(\"Mujeres: Tiempo Final por Rango de Edad\", \nfontsize=14, fontweight='bold')\naxes[1].set_xlabel(\"Rango de Edad\")\naxes[1].set_ylabel(\"Tiempo en Meta (Horas)\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](02_eda_files/figure-html/eda-boxplot-edad-tiempo-output-1.png){#eda-boxplot-edad-tiempo width=1141 height=947}\n:::\n:::\n\n\nEl rendimiento en la maratón se mantiene increíblemente estable hasta los 50 años en ambos sexos, situándose la mediana de tiempo ligeramente por encima de las 3 horas en hombres y en torno a las 3 horas y media en mujeres. Es a partir de la franja de 50-55 años cuando se observa un punto de inflexión, donde los tiempos medios comienzan a subir de forma progresiva.\n\n\n### Cantidad de corredores en cada categoría\n\nEn esta sección, se el objetivo será graficar cuántos corredores hay en cada categoría\n\n::: {#cell-eda-proporcion-categorias .cell execution_count=8}\n``` {.python .cell-code}\nplt.figure(figsize=(10, 6))\n\n# Calculamos porcentajes\ncat_counts = df_boston['athlete_level'].value_counts(normalize=\nTrue).sort_index() * 100\n\nax = sns.barplot(\n    x=cat_counts.index, y=cat_counts.values, \n    palette=\"Blues_d\", hue=cat_counts.index, legend=False\n)\n\nplt.title(\"Distribución de la Población por Nivel de Rendimiento\",\n fontsize=14, fontweight='bold')\nplt.ylabel(\"Porcentaje de Corredores (%)\")\nplt.xlabel(\"Categoría de Atleta\")\nplt.xticks(rotation=15)\n\n# Añadimos las etiquetas de porcentaje sobre las barras\nfor p in ax.patches:\n    ax.annotate(f'{p.get_height():.1f}%', \n                (p.get_x() + p.get_width() / 2., p.get_height()), \n                ha='center', va='bottom', fontsize=11,\n                 fontweight='bold', xytext=(0, 5),\n                textcoords='offset points')\n\nplt.ylim(0, max(cat_counts.values) + 10)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](02_eda_files/figure-html/eda-proporcion-categorias-output-1.png){#eda-proporcion-categorias width=808 height=577}\n:::\n:::\n\n\nLa categorización de los atletas por nivel de rendimiento muestra una estructura piramidal muy clara. La mitad del pelotón (50.4%) se clasifica en el umbral de Principiante (marcas superiores a 3h 30m en hombres y 4h en mujeres), seguido de un 36.0% de corredores Moderadamente entrenados. Por su parte, la élite y los atletas de alto nivel representan una fracción muy baja, de apenas el 0.6% sumando ambos.\n\n### Impacto del clima \n\nUna vez revisados la cantidad de corredores por categoría, en este apartado se va a evaluar la distribución de tiempos por año.\n\n::: {#cell-eda-impacto-clima-visual .cell execution_count=9}\n``` {.python .cell-code}\nplt.figure(figsize=(10, 6))\n\npaleta_clima = [\"#4a6491\", \"#588c7e\", \"#d96459\"]\n\nsns.violinplot(\n    data=df_boston, x='Date', y='official_hours', \n    palette=paleta_clima, inner=\"quartile\", hue='Date', legend=False\n)\n\nplt.title(\"Distribución de Tiempos por Edición (Impacto del Clima)\",\n fontsize=14, fontweight='bold')\nplt.ylabel(\"Tiempo en Meta (Horas)\")\n\n# Ajustamos las etiquetas del eje X para que solo se vea el año\nplt.xticks(ticks=[0, 1, 2], labels=['2015\\n(Frío/Viento)',\n '2016\\n(Templado)', '2017\\n(Calor)'])\n\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](02_eda_files/figure-html/eda-impacto-clima-visual-output-1.png){#eda-impacto-clima-visual width=799 height=541}\n:::\n:::\n\n\nSe observa que a medida que la edición avanza, los tiempos en media parecen ser mayores. Para confirmar esto, se va a realizar un test estadístico sobre la categoría Élite, ya que son los únicos corredores en los que se puede obtener una medida fiable de si el recorrido era más rápido o lento respecto al clima de esa edición\n\n::: {#eda-anova-elite .cell execution_count=10}\n``` {.python .cell-code}\n# 1. Filtramos solo los corredores de Élite\ndf_elite = df_boston[df_boston['athlete_level'] == 'Élite'].copy()\n\n# 2. Creamos la tabla comparativa de medias para la Élite\ntabla_clima = df_elite.groupby('Date').agg(\n    Media_Horas=('official_hours', 'mean'),\n    Desviacion=('official_hours', 'std'),\n    N=('official_hours', 'count')\n).round(3)\n\n# 3. Preparamos los datos para el ANOVA\ngrupos = (\n    [df_elite[df_elite['Date'] == d]['official_hours'] for d in df_boston['Date'].unique()])\nf_stat, p_val = stats.f_oneway(*grupos)\n\nprint(tabla_clima.to_markdown())\n```\n| Date       |   Media_Horas |   Desviacion |   N |\n|:-----------|--------------:|-------------:|----:|\n| 2015-04-20 |         2.372 |        0.174 |  29 |\n| 2016-04-18 |         2.471 |        0.171 |  21 |\n| 2017-04-17 |         2.448 |        0.185 |  36 |\n:::\n\n\n::: {#eda-anova-elite-2 .cell execution_count=11}\n``` {.python .cell-code}\nprint(f\"\\n**Resultado del test ANOVA en Élite:**\")\nprint(f\"- Estadístico F: {f_stat:.4f}\")\nprint(f\"- P-valor: {p_val:.4e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n**Resultado del test ANOVA en Élite:**\n- Estadístico F: 2.2921\n- P-valor: 1.0742e-01\n```\n:::\n:::\n\n\nPor lo que se puede observar en la tabla y en el p-valor, no existen diferencias significativas en sus tiempos medios a lo largo de las 3 ediciones. \n\n\n### Muro por categorías\n\nPor último, vamos a evaluar el número de corredores que sufre el colapso en el muro según el nivel del atleta: \n\n::: {#eda-tabla-muro-categoria .cell execution_count=12}\n``` {.python .cell-code}\n# Agrupamos por categoría y calculamos métricas\nresumen_muro = df_boston.groupby('athlete_level', observed=True).agg(\n    Total_Corredores=('hit_the_wall', 'count'),\n    Sufren_Muro=('hit_the_wall', 'sum')\n).reset_index()\n\n# Calculamos el % dentro de cada categoría\nresumen_muro['%_Impacto_Muro'] = (\n  (resumen_muro['Sufren_Muro'] / resumen_muro['Total_Corredores']) * 100\n).round(2)\n\n# Renombramos para la tabla final\nresumen_muro.columns = ['Categoría', 'Nº Corredores', \n'Casos de Muro', '% del Muro']\n\nprint(resumen_muro.to_markdown(index=False))\n```\n| Categoría                 |   Nº Corredores |   Casos de Muro |   % del Muro |\n|:--------------------------|----------------:|----------------:|-------------:|\n| Principiante              |           39845 |           13164 |        33.04 |\n| Moderadamente entrenado/a |           28452 |            2570 |         9.03 |\n| Muy entrenado/a           |           10262 |             243 |         2.37 |\n| Alto nivel                |             393 |               1 |         0.25 |\n| Élite                     |              86 |               0 |         0    |\n:::\n\n\nA medida que aumenta el nivel de entrenamiento del atleta, la probabilidad de sufrir un colapso en la segunda mitad de la prueba se desploma drásticamente. Mientras que 1 de cada 3 corredores principiantes (33.04%) choca contra el muro —víctimas de una gestión del ritmo menos madura y de una menor adaptación al consumo eficiente de glucógeno—, esta cifra se reduce a un 9.03% en los moderadamente entrenados y cae a un marginal 2.37% en el grupo de muy entrenados.\n\nPor su parte, en las categorías superiores el muro es prácticamente inexistente (0.25% en Alto nivel y 0% en la Élite). Estos datos confirman que el colapso fisiológico no es un evento puramente aleatorio de la distancia de maratón, sino una variable fuertemente predecible y dependiente de la preparación de los atletas.\n\n",
    "supporting": [
      "02_eda_files"
    ],
    "filters": [],
    "includes": {}
  }
}