---
title: "Aprendizaje Supervisado"
---

Este capítulo se divide en dos problemas distintos: 

1. **Problema de clasificación**: Predecir si los corredores "petan" o no en el muro a través de la variable creada en el análisis exploratorio. 

2. **Problema de regresión**: Predecir el tiempo final de los atletas al paso por los 35km. Cabe destacar que en la asignatura de *Análisis de Datos en el Deporte* se realizó un estudio con modelos de regresión y se observó que el parcial que mejores predicciones obtenía era el 35, por lo tanto, ahora vamos a probar varios modelos sobre este parcial para determinar cuál es mejor. 


## Importación de librerías

Comenzamos importando las librerías necesarias

```{python}
#| label: importar-librerias-supervised
#| eval: true
#| echo: true
#| warning: false

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración visual
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

# ==============================================================================
# 1. HERRAMIENTAS DE PREPARACIÓN DE DATOS (PARTICIONADO Y ESCALADO)
# ==============================================================================
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# ==============================================================================
# 2. MODELOS DE CLASIFICACIÓN (Para predecir "hit_the_wall")
# ==============================================================================
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# ==============================================================================
# 3. MODELOS DE REGRESIÓN (Para predecir el tiempo en meta)
# ==============================================================================
from sklearn.linear_model import LinearRegression, Ridge, Lasso # Modelos Lineales Generalizados
from sklearn.tree import DecisionTreeRegressor
import xgboost as xgb # El rey del rendimiento

# ==============================================================================
# 4. MÉTRICAS DE EVALUACIÓN (Para ponerles nota a los modelos)
# ==============================================================================
# Para Clasificación:
from sklearn.metrics import accuracy_score, recall_score, classification_report, confusion_matrix, roc_auc_score
# Para Regresión:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

```

## Carga de datos

Realizamos la carga de datos.

```{python}
#| label: carga-datos-supervised
#| eval: true
#| echo: true
#| warning: false

# Si no os deja cargarlo al trabajar (no al hacer quarto render), en la consola importar os y dejais como directorio de trabajo la carpeta de notebooks

# import os
# os.getcwd (y si no está en notebook, poneis en la consola os.chdir("notebooks"))
df_boston = pd.read_parquet("../data/processed/boston_post_eda.parquet")
```


## Problema de clasificación. Detección de atletas que sufren en el muro. 

Para comenzar esta sección, vamos a realizar la división de nuestro conjunto de datos en Train-Test-Validation. 

Para ello, la mejor opción será realizar un muestreo estratificado ya que hay un 79.78% de corredores que no chocan con el muro `hit_the_wall=0`. 

A continuación, se hace el muestreo estratificado en una proporción 60-20-20 para cada conjunto. Además, se dejan en X las variables predictoras que pueden llegar a usarse (age, gender, country_residence, 5k, 10k, 15k, 20k, half, temp_mean_c, humidity_pct, wind_speed_kmh). 

```{python}
#| label: particion-clasificacion-supervised
#| eval: true
#| echo: true

# 1. SELECCIÓN DE VARIABLES
features_todas = [
    'age', 'gender', 'country_residence', 
    '5k', '10k', '15k', '20k', 'half', 
    'temp_mean_c', 'humidity_pct', 'wind_speed_kmh'
]
target = 'hit_the_wall'


X = df_boston[features_todas]
y = df_boston[target]

# 3. DIVISIÓN ESTRATIFICADA (60/20/20)
# Primer corte: 60% Train / 40% Resto
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.40, random_state=42, stratify=y
)

# Segundo corte: Mitad del resto para Validación (20%) y mitad para Test (20%)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)
```


```{python}
#| label: eliminar-1-supervised
#| eval: true
#| echo: false

del X_temp, y_temp, X, y
```


Una vez tenemos nuestros datos ya divididos, entrenaremos nuestros modelos en *Train*, los evaluaremos en *Test* y cuando tengamos todos los posibles modelos, elegiremos uno para probarlo en *Validation*. 

Cabe destacar que evaluaremos el rendimiento de dichos modelos a través de las métricas: 

- **Accuracy**: Una medida de cómo fallamos en general
- **Recall**: Ya que decirle a un atleta que no va a petar cuando en realidad peta es un error que puede costar muy caro, nuestro objetivo será maximizar dicha métrica, es decir, de todos los que realmente petan, ¿cuántos caza el modelo? 


### K-Vecinos Más Cercanos (K-NN)

El algoritmo de K-Vecinos Más Cercanos (K-NN) es un método de aprendizaje supervisado no paramétrico. A diferencia de otros algoritmos que construyen una ecuación matemática o un árbol de reglas durante el entrenamiento, K-NN es un algoritmo de tipo *lazy learning* (aprendizaje perezoso): no "aprende" un modelo en sí, sino que memoriza todo el conjunto de datos de entrenamiento para usarlo como mapa de referencia durante la predicción.

#### Fundamento del Algoritmo

Para clasificar a un nuevo corredor (es decir, predecir si sufrirá "El Muro" o no), el algoritmo sigue un proceso estrictamente geométrico:

1. **Cálculo de Distancias:** Mide la distancia matemática entre el nuevo corredor y todos los demás corredores presentes en el conjunto de entrenamiento. La métrica por defecto es la Distancia Euclidiana en un espacio n-dimensional:
   $$d(x, y) = \sqrt{\sum_{i=1}^{n} (x_i - y_i)^2}$$

2. **Selección de la Vecindad (K):** Identifica a los $K$ corredores del conjunto de entrenamiento que se encuentran a menor distancia del nuevo individuo. El valor $K$ es un hiperparámetro crítico que se debe definir (generalmente un número impar para evitar empates, como 3, 5 o 7).

3. **Votación Mayoritaria:** El algoritmo observa la etiqueta real (`hit_the_wall`) de esos $K$ vecinos más cercanos. La clase mayoritaria entre ellos será la predicción asignada al nuevo corredor.

#### Aplicación del Algoritmo

Una vez definido el marco teórico, aplicamos el algoritmo: 

```{python}
#| label: knn-entrenamiento-supervised
#| eval: true
#| echo: true

#1. Definimos las variables que vamos a usar: 
variables_usar = ['age', '5k', '10k', '15k', '20k', 'half', 'temp_mean_c', 'humidity_pct', 'wind_speed_kmh']
X_train_knn = X_train[variables_usar]
X_test_knn = X_test[variables_usar]
X_validation_knn = X_val[variables_usar]
#2. Las escalamos
scaler = StandardScaler()
X_train_knn = scaler.fit_transform(X_train_knn)
X_test_knn = scaler.transform(X_test_knn)
X_validation_knn = scaler.transform(X_validation_knn)
#3. Entrenamos el algoritmo
modelo_clasificacion_knn = KNeighborsClassifier(n_neighbors=1)
modelo_clasificacion_knn.fit(X_train_knn, y_train)
#4. Realizamos la predicción en test
predicciones_test = modelo_clasificacion_knn.predict(X_test_knn)

#5. Visualizamos la matriz de confusión
tabla_confusion = pd.crosstab(
    y_test, 
    predicciones_test, 
    rownames=['Realidad (0=No, 1=Sí)'], 
    colnames=['Predicción (0=No, 1=Sí)']
)

print("=== MATRIZ DE CONFUSIÓN (K-NN) ===\n")
print(tabla_confusion)

print("=== EVALUACIÓN DEL MODELO KNN ===")
print(f"Accuracy Global:              {accuracy_score(y_test, predicciones_test):.2%}")
print(f"Recall (Detección del Muro):  {recall_score(y_test, predicciones_test, pos_label = 1):.2%}")

```

Comenzamos estableciendo un modelo base utilizando K-NN. Como era de esperar ante un dataset desbalanceado (80/20), el algoritmo basado en distancias fue incapaz de identificar los colapsos, logrando un Recall máximo del 33% asumiendo un riesgo extremo de sobreajuste ($K=1$). Esto justifica la necesidad de evolucionar hacia algoritmos basados en árboles que permitan un balanceo de pesos matemático. 

```{python}
#| label: eliminar-2-supervised
#| eval: true
#| echo: false

del tabla_confusion, features_todas, X_test_knn, X_train_knn, variables_usar, predicciones_test
```

### Árbol de Decisión

El Árbol de Decisión (*Decision Tree*) es un algoritmo de aprendizaje supervisado no paramétrico que construye un modelo predictivo basado en una secuencia jerárquica de reglas lógicas. A diferencia de métodos basados en distancias (como K-NN) o en ecuaciones algebraicas (como la Regresión Lineal), el árbol divide el conjunto de datos iterativamente realizando preguntas binarias sobre las variables predictoras.

#### Funcionamiento y Criterio de Corte
En cada nodo, el algoritmo evalúa todas las características disponibles (edad, ritmos, país, etc.) y selecciona el punto de corte que mejor separa a los corredores según la variable objetivo (`hit_the_wall`). Para medir la calidad de esta separación, utiliza métricas matemáticas de "pureza", siendo la más común el **Índice de Impureza de Gini**. El proceso se ramifica de forma descendente hasta alcanzar un criterio de parada definido por el analista (por ejemplo, una profundidad máxima, `max_depth`) para evitar el sobreajuste (*overfitting*).

### Aplicación del Algoritmo

A continuación, se realiza el algoritmo. La idea será coger las variables categóricas como el país y binarizarlas, en vez de dejar todos los posibles países, ya que son muchos. De esta manera, logramos una regla lógica de si el corredor es o no de los estados unidos. Tras ello, entrenamos el algoritmo: 

```{python}
#| label: entrenamiento-arbol-clasificacion
#| eval: true
#| echo: true

X_train_tree = X_train.copy()
X_test_tree = X_test.copy()
X_val_tree = X_val.copy()
# Binarizamos la variable país
X_train_tree['is_USA'] = (X_train_tree['country_residence'] == 'USA').astype(int)
X_test_tree['is_USA']  = (X_test_tree['country_residence'] == 'USA').astype(int)
X_val_tree['is_USA']  = (X_test_tree['country_residence'] == 'USA').astype(int)

# Convertimos Género (1 = Mujer, 0 = Hombre)
X_train_tree['is_Female'] = (X_train_tree['gender'] == 'F').astype(int)
X_test_tree['is_Female']  = (X_test_tree['gender'] == 'F').astype(int)
X_val_tree['is_Female']  = (X_test_tree['gender'] == 'F').astype(int)
columnas_a_borrar = ['country_residence', 'gender']
X_train_tree.drop(columns=columnas_a_borrar, inplace=True)
X_test_tree.drop(columns=columnas_a_borrar, inplace=True)
X_val_tree.drop(columns=columnas_a_borrar, inplace=True)


modelo_clasificacion_arbol = DecisionTreeClassifier(
    class_weight='balanced', 
    max_depth=7,             
    random_state=42
)

modelo_clasificacion_arbol.fit(X_train_tree, y_train)

predicciones_arbol = modelo_clasificacion_arbol.predict(X_test_tree)

tabla_arbol = pd.crosstab(
    y_test, predicciones_arbol, 
    rownames=['Realidad (0=No, 1=Sí)'], colnames=['Predicción (0=No, 1=Sí)']
)

acc_arbol = accuracy_score(y_test, predicciones_arbol)
rec_arbol = recall_score(y_test, predicciones_arbol, pos_label=1)

print("=== MATRIZ DE CONFUSIÓN (ÁRBOL BALANCEADO) ===\n")
print(tabla_arbol)
print("\n=== EVALUACIÓN ===")
print(f"Accuracy Global:              {acc_arbol:.2%}")
print(f"Recall (Detección del Muro):  {rec_arbol:.2%}")
```

Este modelo, en comparación con el anterior, tiene mucha más *Recall* pero menos *Accuracy*. 

### Random Forest

(hacer el modelo)



### Selección del mejor modelo y predicción en el conjunto de Validación

Tras haber entrenado y probado en test los 3 modelos anteriores, el que obtiene mejores resultados es el modelo de XXXXXXX

Por ello, se realizan las predicciones en el conjunto de validation: 


```{python}
#| label: validacion-clasificacion-supervised
#| eval: true
#| echo: true


#1. Elegimos el modelo entre los tres, modelo_clasificacion_arbol, rforest o knn
predicciones_validacion = modelo_clasificacion_arbol.predict(X_val_tree)

tabla_arbol = pd.crosstab(
    y_test, predicciones_validacion, 
    rownames=['Realidad (0=No, 1=Sí)'], colnames=['Predicción (0=No, 1=Sí)']
)

acc_arbol = accuracy_score(y_test, predicciones_validacion)
rec_arbol = recall_score(y_test, predicciones_validacion, pos_label=1)

print("=== MATRIZ DE CONFUSIÓN (ÁRBOL BALANCEADO) ===\n")
print(tabla_arbol)
print("\n=== EVALUACIÓN ===")
print(f"Accuracy Global:              {acc_arbol:.2%}")
print(f"Recall (Detección del Muro):  {rec_arbol:.2%}")
```


```{python}
#| label: eliminar-3-supervised
#| eval: true
#| echo: false

# Eliminamos todas las variables menos el df_boston para el problema de regresión
```


## Problema de regresión. Predicción de tiempo final según sus datos hasta el parcial 35km

El objetivo de esta sección es predecir los tiempos finales de los corredores con los datos hasta el parcial de 35km. Por lo tanto, 